# Generated by Django 5.0.3 on 2024-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_genero_usuario_autor_editora_livro_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=100)),
                ('leitor', models.CharField(max_length=100)),
                ('dataemprestimo', models.DateField()),
                ('datadevolucao', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
